### PR TITLE
travis: add PHP 7.0 and 7.1

### PR DESCRIPTION
**Pull request by TomasVotruba**
Just noticed Phinx and it looks great.

Are you still using this for database migrations?

### CODE REVIEW

**Comment by castamir** [comment]
Yes, I still do. I stopped developing new PHP apps (I've moved towards frontend technologies) but I still maintain all Joseki libs as well as LeanMapper.

------
I'll check error in build tomorrow, I'm on my way to Prague right now (Sum 41 concert ;) )

**Comment by TomasVotruba** [comment]
We're using it directly with `phinx.yml`. So I was wondering, if you see any added value by integrating this to specific framework. It's a vendor lock.

Why did you move to frontend techs?

Sum 41! Nice! :+1:

**Comment by castamir** [comment]
When I started using Phinx, it was nice, but still under heavy development of custom database layer. I didn't need that. I had dibi ;)

One year ago, I had to decide, what to do next. I couldn't find anything in developing PHP apps, what could push me forward. In a result, I've changed my job and area of interest. Right now, I focus on developing client apps in Angular2 framework (and even it is still a javascript framework, it looks really great).

**Comment by TomasVotruba** [comment]
I think it works with any database layer, it's not related at all.

I see. What was your recent PHP path before switching? Have you tried different PHP frameworks?

**Comment by castamir** [comment]
Nette (most of the time) with Symphony components (for edge cases and/or release tasks such as database migrations). I've migrated my last app into freshly released PHP7 and then I quit :D

**Comment by TomasVotruba** [comment]
Well, I got same situation :D got stuck with one framework and felt like I need more, better, cleaner...

I keep learning faster and faster. 2 years ago Symfony, now Laravel, eager for new and high quality packages. And PHP 7 and PHP 7.1 saved my PHP life.

Btw, would care for giving some small talk or article about this? I think it's very interesting topic, that many people wonder about.

**Comment by castamir** [comment]
Well... why not? Lets continue somewhere else ([gitter](https://gitter.im/Joseki) or email)

**Comment by TomasVotruba** [comment]
Ok. I saw your name on Slack, are you there?

**Comment by TomasVotruba** [comment]
Btw, would you be interesting in PR bumping minimal dependency + code to PHP 7?

Since 7.x are only supported versions and Nette 3.0 is going to be PHP 7.1, I think it makes great sense.

**Comment by castamir** [comment]
Feel free to send a PR ;-)

**Comment by TomasVotruba** [comment]
So I was really trying to make some changes, but I got some bug on PHP 7.1 for mysqli extension that is not in Google yet :D 

Too bad, I really look forward to this.

**Pull request merged**
